### ISSUE TITLE
Content-Web Pipeline Build is failing

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Cloud-native-applications#124]
In Exercise 2 -> Task 7:-> step 4, I'm getting error in helm init while building the pipeline.
The build is failing due to helm. I was able to get past error by editing the pipeline to install helm version v2.8.2 instead of pointing to the latest.
But, I faced another issue at helm update step

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  We will review your issue soon.

Tim

**Comment by inatale** [comment]
The same for me as well. Not only on Init step bu also on package task command (could be resolved by using save: false - force not to save locally). And than new errors on init step (like --upgrade flag not found).

**Comment by Gvashi** [comment]
@timahenning can you please take a look .

**Comment by jamesrcounts** [comment]
This is most likely related to the release of Helm 3 which came out very recently and has significant differences from Helm 2.

**Comment by aaronpburke** [comment]
I was experiencing this same issue and the solution proposed by @jamesrcounts fixed it. Please note that in the final YAML file, you'll have to make this change in two places (the "Build and Push Helm Chart" and "Deployment to AKS" jobs).

**Comment by Gvashi** [comment]
I updated the helm installer task to force a version of helm 2 in two places, but still I got the error in Azure CLI Task in "Build and Push Helm Chart": 
/home/vsts/work/_temp/azureclitaskscript1574770526748.sh: line 7: failOnStandardError:: command not found
##[error]Script failed with error: Error: The process '/bin/bash' failed with exit code 127

**Comment by jamesrcounts** [comment]
#131 Updates the lab to support Helm 3.
