### ISSUE TITLE
Before the Hands on Lab - Task 6 Step 6 error.

### ISSUE THREAD

**Issue by VaSquirrel** [microsoft/MCW-Cloud-native-applications#125]
I receive this error consistently in this lab.  I tried US West and US South Central.  I deleted and recreated a different Resource group.
I am using a Pay-As-You go Azure account.

az group deployment create --resource-group fabmedical-Ray --template-file azuredeploy.json --parameters azuredeploy.parameters.json
<<-- Error Message -->>
	ray@Azure:~/MCW-Cloud-native-applications/Hands-on lab/arm$ az group deployment create --resource-group fabmedical-Ray --template-file azuredeploy.json --parameters azuredeploy.parameters.json
	Azure Error: InvalidTemplateDeployment
	Message: The template deployment failed with error: 'The resource with id: '/subscriptions/5f511c31-1d3a-4ce1-953d-d8f61b14ecb2/resourceGroups/fabmedical-Ray/providers/Microsoft.Compute/virtualMachines/fabmedical-Ray' failed validation with message: 'The requested size for resource '/subscriptions/5f511c31-1d3a-4ce1-953d-d8f61b14ecb2/resourceGroups/fabmedical-Ray/providers/Microsoft.Compute/virtualMachines/fabmedical-Ray' is currently not availablein location 'westus' zones '' for subscription '5f511c31-1d3a-4ce1-953d-d8f61b14ecb2'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'.

ray@Azure:~/MCW-Cloud-native-applications/Hands-on lab/arm$

**Comment by VaSquirrel** [comment]
Originally, I set all of this up using West US per the example.  So the resource group fabmedical-Ray location is West US.  When the error first occurred I followed recommendations to change location in the deploy parameters file to a new region South Central US.
Turns out the deploy script uses "[resourceGroup().location]" for many things so it still tries to create the server in West US.
So, do I have to delete the Resource Group and start over?
Can I edit the deploy script to force "location" to South Central US? 
Can I change the Size ?

**Comment by vraposo** [comment]
To facilitate the deployment of all the resources in the same location, the location used by almost all the resources is based out of the resource group itself. The easiest/fastest way to deploy in another region is to do so to a resource group created in that target region.

Regarding changing the VM size, it's possible to do so by modifying the `virtualMachineSizeLinux` variable, but the virtual machine size recommendations should be taken into account to ensure the successfulness of the lab steps.

**Comment by timahenning** [comment]
Closing the issue due to lack of activity.  Please let us know if you have additional questions on this issue.
