### ISSUE TITLE
Stuck at task #7 step 20

### ISSUE THREAD

**Issue by trigolddev** [microsoft/MCW-Cloud-native-applications#127]
I was able to follow the instructions all the way down to this Task #7, step 20. I don't know where to start from there. I do not see content-web folder using the cloud shell window. In other words, it seems that the content-web folder was not created somehow. Are we expecting that folder to be generated when the repository (named as content-web) was created through UI.  I do see the repository content-web created though. Please help.

**Comment by jamesrcounts** [comment]
Sounds like you are in Before the Hands On Lab, Task 7: https://github.com/microsoft/MCW-Cloud-native-applications/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Cloud-native%20applications.md#task-7-setup-azure-devops-project

In Step 2 of this task you should have navigated to one of these folders:

 `cd ~/MCW-Cloud-native-applications/Hands-on\ lab/lab-files/developer/`

or 

`cd ~/MCW-Cloud-native-applications/Hands-on\ lab/lab-files/infrastructure/`

in cloud shell. 

Either of these should have `content-web` as a sub directory

**Comment by jamesrcounts** [comment]
We did not encounter this issue while testing #131
