### ISSUE TITLE
Images don't appear in the workshop

### ISSUE THREAD

**Issue by santimacnet** [microsoft/MCW-Cloud-native-applications#128]
The images in the workshop aren't displayed in the browser.

**Comment by timahenning** [comment]
Hi @santimacnet ,

Can you provide a little more information regarding this issue?  Can you provide us the exact area in the lab you experienced this issue?

Thanks,

TIm

**Comment by santimacnet** [comment]
For instance, Please check this url: https://github.com/microsoft/MCW-Cloud-native-applications/tree/master/Hands-on%20lab/media the images dont appear if you click in any of them and if you are working.

And in this link: https://github.com/microsoft/MCW-Cloud-native-applications/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Cloud-native%20applications.md, is the tutorial step by step to configure the enviroment in Azure dont show any image in the browser only the alt-text.

**Comment by jamesrcounts** [comment]
I have not been able to replicate this behavior by following either link.

**Comment by DawnmarieDesJardins** [comment]
@santimacnet 
Hello!  Please advise if it's a single image you're not seeing, or if all of the images are missing for you.  I've viewed each workshop on the repo, and from the HTML pages, and they show for me.
Thank you.

**Comment by santimacnet** [comment]
Hi!! My apologies in advance, it was a problem with my browser and plugins.

**Comment by DawnmarieDesJardins** [comment]
All good, thank you so much for letting us know.
