### ISSUE TITLE
 Helm init Fails in Exercise #2 - Task #4

### ISSUE THREAD

**Issue by santimacnet** [microsoft/MCW-Cloud-native-applications#130]
Hi, you can check the issue in this section:

1. **Cloud-native applications - Developer edition hands-on lab step-by-step**
2. **Exercise 2: Deploy the solution to Azure Kubernetes Service**
3. **Task 4: Deploy a service using a Helm chart** 

When I try execute this command: _$ helm init --service-account tiller_
Its produces this message: Error: _unknown flag: --service-account_

I think the problem is because in Azure shell currently uses Helm 3.0 and Tiller was removed in this version. Thus, helm init is no longer necessary. 

Please check this link: https://helm.sh/docs/faq/#removal-of-tiller

**Comment by vraposo** [comment]
Might be related with what @jamesrcounts originally posted in https://github.com/microsoft/MCW-Cloud-native-applications/issues/124#issuecomment-557121268_

**Comment by jamesrcounts** [comment]
Should be fixed by #131

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #131
