### ISSUE TITLE
Content-Web Pipeline Build is failing

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Cloud-native-applications#132]
In Exercise 2 -> Task 7:-> step 4, 
1.Command "helm install --name web ./web" showing an error ,
2. I updated the helm installer task to force a version of helm 2 in two places, but still I got the error in Azure CLI Task in "Build and Push Helm Chart":
/home/vsts/work/_temp/azureclitaskscript1574770526748.sh: line 7: failOnStandardError:: command not found
##[error]Script failed with error: Error: The process '/bin/bash' failed with exit code 127

@DawnmarieDesJardins  can you please take a look asap.

**Comment by jamesrcounts** [comment]
Issues with helm should be resolved in #131

**Comment by timahenning** [comment]
We have a PR about to be merged any day now.  I apologize.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #131
