### ISSUE TITLE
Helm cmd gives error: In az cli Helm 3

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Cloud-native-applications#134]
Helm cmd gives error: In az cli Helm 3 but according to lab guide we are using older version of Helm. So have to use Helm v2.1.6. 
please update this as v2.1.6

**Comment by jamesrcounts** [comment]
Yesterday the team merged a PR #131 that updates the lab guide to Helm 3 so that it matches the default installed in Azure Cloud Shell.  Are you saying parts of the lab still refer to Helm 2?

**Comment by DawnmarieDesJardins** [comment]
Closing issue with no further contact from field.  Assuming fixed with December test/fix
