### ISSUE TITLE
Ingress Error on Exercise 4 Task 5

### ISSUE THREAD

**Issue by wely** [microsoft/MCW-Cloud-native-applications#137]
I was doing [this](https://github.com/microsoft/MCW-Cloud-native-applications/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Cloud-native%20applications%20-%20Developer%20edition.md#task-5-configure-kubernetes-ingress) but encountered the error of: **Answer: 404 Not Found
nginx/1.17.6**

I notice that the NGINX Ingress Controller image isn't the community version so i did these and it eventually works for me:
1.	Delete the existing ingress (if any) => helm delete ingress-controller -n kube-system
2.	helm repo add stable https://kubernetes-charts.storage.googleapis.com/
3.	helm install nginx stable/nginx-ingress
4.	Run “kubectl get svc” to get the new external IP and update the dns name via ‘update-ip.sh’
5.	Retry the URL and check if it works.

**Comment by vraposo** [comment]
Fixed in PR #138.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #138
