### ISSUE TITLE
Shall we move the provisioning of AKS with VM Scaleset

### ISSUE THREAD

**Issue by wely** [microsoft/MCW-Cloud-native-applications#139]
VMSS enables much more scenario such as Nodepool and Cluster Autoscaler.
This current lab (and the ARM template) uses the legacy VM, not VMSS.

Shall we consider to move to VMSS?

**Comment by vraposo** [comment]
Fixed in PR #144 .

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #144
