### ISSUE TITLE
Before HOL - SSH Key

### ISSUE THREAD

**Issue by adjinugroho** [microsoft/MCW-Cloud-native-applications#140]
Task : **Task 6 : Deploy ARM Template**
File : **azuredeploy.parameters.json**
Key : **VirtualMachineAdminPublicKeyLinux**
Error Summary : **SSH Key** 
Error Description :
I think I need to input SSH key fingerprint generated when create SSH key in Task 4 because in step 6, I need to keep cloud shell open because I will need it in later task.

This error lead to re-create VM which mean take some time.

I think you need add one step to get SSH key in **.ssh/fabmedical.pub** file. We can put this step either in Task 4 or Task 6. And I think **cd .ssh** command also need to documented on this step in case we are not familiar enough with Linux.

**Comment by vraposo** [comment]
Fixed in PR #144 .

**Comment by DawnmarieDesJardins** [comment]
Closing issues as resolved with merge of PR #144
