### ISSUE TITLE
HOL - Exercise 2 - Task 1 : Tunnel into the Azure Kubernetes Service cluster

### ISSUE THREAD

**Issue by adjinugroho** [microsoft/MCW-Cloud-native-applications#141]
I was doing [Exercise 2 Task 1](https://github.com/microsoft/MCW-Cloud-native-applications/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Cloud-native%20applications%20-%20Developer%20edition.md#task-1-tunnel-into-the-azure-kubernetes-service-cluster). 

When I run step 5 command, _az aks browse --name fabmedical-SUFFIX --resource-group fabmedical-SUFFIX_, new tab opened json-like file instead opened kubernetes desktop.

![Capture](https://user-images.githubusercontent.com/10370492/74605905-0f356580-5107-11ea-813b-dac4b767fd24.JPG)

**Comment by wely** [comment]
As the AKS engineering team is working on the fix which will be rolled out soon, please append the following at the end of the URL:

"api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/#!/overview?namespace=default"

Example: 
https://gw.region.console.azure.com/n/xxx/xxx/proxy/8001/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/#!/overview?namespace=default

**Comment by wely** [comment]
I was informed by Azure Support, to workaround this, we can also perform:

**Enable the AKS-Preview extension in Cloud Shell: az extension add --name aks-preview**

**Comment by vraposo** [comment]
Fixed in PR #144 .

**Comment by timahenning** [comment]
We are finishing up the review today.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #144
