### ISSUE TITLE
CosmosPairedLocationName is redundant?

### ISSUE THREAD

**Issue by wely** [microsoft/MCW-Cloud-native-applications#142]
Step: https://github.com/microsoft/MCW-Cloud-native-applications/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Cloud-native%20applications.md#task-6-deploy-arm-template

I wonder if we really need to enter the CosmosPairedLocationName in the json file since we already have the "CosmosPairedLocation". Is it redundant?

**Comment by vraposo** [comment]
*CosmosLocationName* and *CosmosPairedLocationName* can't be removed, since they are required as per the template reference documentation.

The only field we can remove is *CosmosPairedLocation*, since it's only used as part of the easy-to-read id generation for the fail-over geographical location, although that is actually what the portal actually does.

**Comment by vraposo** [comment]
@wely do you have any extra feedback on this subject? We are trying to push updates to the lab and would like to take this issue into account accordingly.

Thanks.

**Comment by wely** [comment]
Hi @vraposo, yeah i realize that LocationName is required from the CosmosDB ARM Template. 
![image](https://user-images.githubusercontent.com/1658657/74997359-de4f8a80-5490-11ea-9282-b690e7c37b68.png)

Not really sure why we need to have the "LocationName" since we already have the "location"

@markjbrown can you advise?

**Comment by markjbrown** [comment]
locationName is probably for a replication region in case you want to put the replica in a region that is different than the ARM resource meta data.

best way to tell is look in azuredeploy.json and see. My guess is location is used to set the ARM resource location and locationName is used to specify a replica region.

**Comment by wely** [comment]
@markjbrown 
Below is the screenshot of the ARM creation template from Azure Portal.

This is what i mean:
![image](https://user-images.githubusercontent.com/1658657/74999240-15746a80-5496-11ea-9fd2-53c0fcc74382.png)

Why do we need to specify the primary "locationName" as "West US", while we already have "location" as "westus"?

Why do we need to specify the  "pairedLocationName" as "East US", while we already have "pairedLocation" as "eastus"?

**Comment by markjbrown** [comment]
Went and round azuredeploy.json for this lab. Pretty easy to see what these values are used for here below. Pasted a snippet of the cosmos account arm json.

CosmosLocation is where the ARM metadata is stored.
CosmosLocationName is the primary write region.
CosmosPairedLocationName is the secondary read region.

You _**could_** remove the locations[] array below and our resource provider will deploy with a single region specified for the ARM metadata is stored in CosmosLocation. 

But I have no idea if that is a good idea or not. I didn't create this lab. Just telling you how our RP works.


"type": "Microsoft.DocumentDb/databaseAccounts",
            "apiVersion": "2015-04-08",
            "name": "[variables('cosmosName')]",
            "location": "[parameters('CosmosLocation')]",
            "kind": "[variables('cosmosApi')]",
            "properties": {
                "databaseAccountOfferType": "[variables('cosmosSku')]",
                "locations": [
                    {
                        "id": "[concat(variables('cosmosName'), '-', parameters('CosmosLocation'))]",
                        "failoverPriority": 0,
                        "locationName": "[parameters('CosmosLocationName')]"
                    },
                    {
                        "id": "[concat(variables('cosmosName'), '-', parameters('CosmosPairedLocation'))]",
                        "failoverPriority": 1,
                        "locationName": "[parameters('CosmosPairedLocationName')]"
                    }
                ],

**Comment by wely** [comment]
@markjbrown Maybe i have confused you by raising the issue in this lab. Sorry about that.

Forget about this lab for the moment. 

Let's take a step back, i just wondering: during the Azure Cosmos DB Account creation step in the Azure Portal :

- Why do we need to specify the primary "**locationName**" as "**West US**", while we already have "**location**" as "**westus**"?
- Why do we need to specify the "**pairedLocationName**" as "**East US**", while we already have "**pairedLocation**" as "**eastus**"?

![image](https://user-images.githubusercontent.com/1658657/75000524-8a956f00-5499-11ea-8f68-4ff94bf07cf0.png)

**Comment by markjbrown** [comment]
yeah either is ok to pass to any resource provider in Azure. ARM understands both formats. 

If someone wanted to modify the ARM template that did away with one of those they easily could, provided they know how to modify the ARM template :)

**Comment by wely** [comment]
@markjbrown 
i tried to remove "locationName" in the template, just define "location":

Here's the template.json file:
{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "name": {
            "type": "String"
        },
        "location": {
            "type": "String"
        },
        "defaultExperience": {
            "type": "String"
        },
        "isZoneRedundant": {
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.DocumentDb/databaseAccounts",
            "apiVersion": "2019-12-12",
            "name": "[parameters('name')]",
            "location": "[parameters('location')]",
            "tags": {
                "defaultExperience": "[parameters('defaultExperience')]",
                "hidden-cosmos-mmspecial": ""
            },
            "kind": "GlobalDocumentDB",
            "properties": {
                "databaseAccountOfferType": "Standard",
                "locations": [
                    {
                        "id": "[concat(parameters('name'), '-', parameters('location'))]",
                        "failoverPriority": 0
                    }
                ],
                "enableMultipleWriteLocations": false,
                "isVirtualNetworkFilterEnabled": false,
                "virtualNetworkRules": [],
                "ipRangeFilter": "",
                "dependsOn": [],
                "capabilities": []
            }
        }
    ],
    "outputs": {}
}

and here's parameter:
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "name": {
      "value": "deletelater"
    },
    "location": {
      "value": "westus"
    },
    "defaultExperience": {
      "value": "Core (SQL)"
    },
    "isZoneRedundant": {
      "value": "false"
    }
  }
}

I got error during deploying this thru Azure portal:
![image](https://user-images.githubusercontent.com/1658657/75001703-18268e00-549d-11ea-85c8-9fde9bae11f4.png)

So the conclusion is both (not either) "location" and "locationName" are required?
This is why i'm wondering why Cosmos requires both "location" and "locationName" 

;) any idea?

**Comment by markjbrown** [comment]
It's asking for it because you have the locations[] array in your template. Just remove it completely. See here below. Removed other stuff you don't need or aren't using either.


{
"$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
"contentVersion": "1.0.0.0",
"parameters": {
"name": {
"type": "String"
},
"location": {
"type": "String"
},
"defaultExperience": {
"type": "String"
},
"isZoneRedundant": {
"type": "String"
}
},
"variables": {},
"resources": [
{
"type": "Microsoft.DocumentDb/databaseAccounts",
"apiVersion": "2019-12-12",
"name": "[parameters('name')]",
"location": "[parameters('location')]",
"tags": {
"defaultExperience": "[parameters('defaultExperience')]",
"hidden-cosmos-mmspecial": ""
},
"kind": "GlobalDocumentDB",
"properties": {
"databaseAccountOfferType": "Standard"
}
}
],
"outputs": {}
}

**Comment by wely** [comment]
> It's asking for it because you have the locations[] array in your template. Just remove it completely. See here below. Removed other stuff you don't need or aren't using either.
> 
> {
> "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
> "contentVersion": "1.0.0.0",
> "parameters": {
> "name": {
> "type": "String"
> },
> "location": {
> "type": "String"
> },
> "defaultExperience": {
> "type": "String"
> },
> "isZoneRedundant": {
> "type": "String"
> }
> },
> "variables": {},
> "resources": [
> {
> "type": "Microsoft.DocumentDb/databaseAccounts",
> "apiVersion": "2019-12-12",
> "name": "[parameters('name')]",
> "location": "[parameters('location')]",
> "tags": {
> "defaultExperience": "[parameters('defaultExperience')]",
> "hidden-cosmos-mmspecial": ""
> },
> "kind": "GlobalDocumentDB",
> "properties": {
> "databaseAccountOfferType": "Standard"
> }
> }
> ],
> "outputs": {}
> }

cool @markjbrown . this works! So we can conclude that **"locationName" isn't required when we provision single geo CosmosDB**.

I have one more question, please bear with me :)

For the creation with Geo-Redundancy, is the "pairedLocationName" required?
I've tried to remove it as can be seen in the following files but apparently it doesn't pass the deployment validation. 
[cosmos-geo-template.txt](https://github.com/microsoft/MCW-Cloud-native-applications/files/4234508/cosmos-geo-template.txt)
[cosmos-geo-param.txt](https://github.com/microsoft/MCW-Cloud-native-applications/files/4234507/cosmos-geo-param.txt)

**Comment by markjbrown** [comment]
There is no Geo-Redundancy option like you see in the portal. If you want multiple regions, use locations array and specify all regions.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wely** [comment]
okay, thanks @markjbrown
