### ISSUE TITLE
Before the Hands on Lab - Task 6: Azure group deployment is deprecated

### ISSUE THREAD

**Issue by MAPeacock86** [microsoft/MCW-Cloud-native-applications#145]
Running the following command in task 6 displays a warning that "...'group deployment' is depricated and will be removed in a future release. Use 'deployment group' instead."

**Comment by nelsonflorez11** [comment]
I still get the error
nelson@Azure:~/MCW-Cloud-native-applications/Hands-on lab/arm$ az  deployment group create --resource-group aksdemo-nf --template-file azuredeploy.json --parameters azuredeploy.parameters.json
{'additional_properties': {}, 'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'azuredeploy' is not valid according to the validationprocedure. The tracking id is '06f23d71-7e55-4334-b589-e2ec57a8e27c'. See inner errors for details.", 'target': None, 'details': [<azure.mgmt.resource.resources.v2019_07_01.models._models_py3.ErrorResponse object at 0x7f472a96a588>, <azure.mgmt.resource.resources.v2019_07_01.models._models_py3.ErrorResponse objectat 0x7f472a96a0b8>], 'additional_info': None}

**Comment by andresmmujica** [comment]
finding the right kubernetes version and replacing the value in azuredeploy.json solves this issue


        - "kubernetesVersion": "1.15.5",
        + "kubernetesVersion": "1.16.7",

**Comment by timahenning** [comment]
We’re working on a solution and should have something released in a few days.

**Comment by vraposo** [comment]
Your contribution is now part of PR #150.

Regarding the proposed AKS version upgrade, such a change involves various risks at this point in time, because v1.16.7 uses kubernetes-dashboard v2.0.0-beta8 which is not a stable version (and has been displaying some issues at the moment). The version has been upgraded to the latest v1.15 patch (v1.15.10).
