### ISSUE TITLE
Exercise 1 Task 3 -  Create and run a Docker application

### ISSUE THREAD

**Issue by andresmmujica** [microsoft/MCW-Cloud-native-applications#147]
During this task we're facing this issue, 

Type the following command to create a Docker image for the web application.

docker image build -t content-web .

Step 11/15 : RUN ng build
 ---> Running in 9ceb88eeb599
Generating ES5 bundles for differential loading...
An unhandled exception occurred: [BABEL] /usr/src/app/dist/content-web/main-es2015.js: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "/usr/src/app/node_modules/@babel/preset-env/lib/index.js")
See "/tmp/ng-ruUQkr/angular-errors.log" for further details.
The command '/bin/sh -c ng build' returned a non-zero code: 127

**Comment by andresmmujica** [comment]
Changing in tsconfig.json


    "target": "es2015",
   
to 

    "target": "es5",

seems to solve the issue

**Comment by CedricSteenbeke** [comment]
Ran into the same issue while building the container. The solution posted above seems to work. 
@andresmmujica  will you create a pull request for this?

**Comment by timahenning** [comment]
We’re working on a solution and should have something released in a few days.

**Comment by vraposo** [comment]
You're contribution is now part of PR #150 which also includes the changes required for the Developer version.
