### ISSUE TITLE
Exercise 2 Task 2 - api connect to cosmosdb

### ISSUE THREAD

**Issue by CedricSteenbeke** [microsoft/MCW-Cloud-native-applications#148]
Getting an exception when trying to connect to CosmosDB with the secret configured.
it seems to have access to the secret and it's using it but there is not connection possible to the cosmosdb instance. Cosmosdb is allowing connections.
![image](https://user-images.githubusercontent.com/6039016/77251220-1a6b3c00-6c45-11ea-86d3-5dfeb62c27bb.png)

```
> content-api@0.0.0 start /usr/src/app
> node ./server.js
Listening on port 3001
Could not connect to MongoDB!
MongooseServerSelectionError: getaddrinfo EAI_AGAIN fabmedical-mks.documents.azure.com
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! content-api@0.0.0 start: `node ./server.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the content-api@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-22T13_52_09_675Z-debug.log
```

**Comment by timahenning** [comment]
We’re working on a solution and should have something released in a few days.

**Comment by vraposo** [comment]
@CedricSteenbeke we were not able to reproduce the problem you mentioned. Is it possible to provide the actual value of the configured secret (please redact the password) to take a look? Thanks.

**Comment by CedricSteenbeke** [comment]
@vraposo below my redacted secret value for the mongodb secret:
`mongodb://fabmedical-aks:VTRAdw3ugP97MiVLXbkIH5StHFYgg%3D%3D@fabmedical-mks.documents.azure.com:10255/contentdb?ssl=true&replicaSet=globaldb`

The deployment config for API
    

> spec:
>       containers:
>       - env:
>         - name: MONGODB_CONNECTION
>           valueFrom:
>             secretKeyRef:
>               key: db
>               name: mongodb
>         image: fabmedicalmks.azurecr.io/content-api


And for sake of doing a sanity check i exported my secret references:

> kubectl get secrets
> NAME                        TYPE                                  DATA   AGE
> default-token-7s6hp         kubernetes.io/service-account-token   3      6d17h
> mongodb                     Opaque                                1      4d14h
> sh.helm.release.v1.web.v1   helm.sh/release.v1                    1      3d21h
> sh.helm.release.v1.web.v2   helm.sh/release.v1                    1      3d20h
> sh.helm.release.v1.web.v3   helm.sh/release.v1                    1      3d20h
> web-token-r2hvt             kubernetes.io/service-account-token   3      3d21h

**Comment by vraposo** [comment]
@CedricSteenbeke from what I can read in your YAML file, it seems that either something happened during your copy-paste to here or it's something wrong with it, because the environment definition is not below the *image* property as it should.

Can you confirm which of the above options is it? Thanks.

**Comment by CedricSteenbeke** [comment]
Removed the deployment and redid it from scratch a 3e time.
First deployment i must have messed up the secret
second deployment was probably what you idicated above.
third deployment shows that it can connect to cosmosdb. 
Thank you for pointing out my mistake in the yaml!! sorry
