### ISSUE TITLE
Security Alerts - for next review

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Cloud-native-applications#152]
GitHub security alerts, closed as acceptable risk for now, please review and incorporate into next test/fix or update.

![Annotation 2020-04-06 113138](https://user-images.githubusercontent.com/39317565/78592665-49171400-77fa-11ea-9c0c-0b3ac8a15d32.png)

**Comment by crpietschmann** [comment]
What project is this for?
This MCW does not contain a `Hands-on lab/Lab-files/azure-iot-pcs-remote-monitoring-dotnet` folder.

**Comment by DawnmarieDesJardins** [comment]
@crpietschmann 
Hi Chris.  I would have copy/pasted from the security page on this repo into here for future review.  If this no longer applies, or I made a copy/paste error, go ahead and close out the issue, we can readdress if it comes up again.  Thank you! DD

**Comment by crpietschmann** [comment]
@DawnmarieDesJardins Could you close this one out? I don't have permissions.

**Comment by DawnmarieDesJardins** [comment]
Absolutely...thanks for the review!
