### ISSUE TITLE
kubernetes version "1.15.10" is not supported 

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Cloud-native-applications#159]
The given kubernetes version "1.15.10" in lab guide  is no more supported in azure. can you please check .

**Comment by DawnmarieDesJardins** [comment]
Hi Gvashi,
We are currently working on an update for this workshop and we'll be publishing the new version soon.  Your issue has more than likely been addressed there but I'm adding a tag to PR #157 to make sure.
Thank you

**Comment by waltermyersiii** [comment]
Gvashi, you can use 1.15.11.

**Comment by waltermyersiii** [comment]
And yes, we have an update coming soon.

**Comment by crpietschmann** [comment]
The latest update to the MCW has been updated to use "1.15.11" which is a supported version.
