### ISSUE TITLE
Kubernetes Version no longer Supported

### ISSUE THREAD

**Issue by arnoldojperozo** [microsoft/MCW-Cloud-native-applications#164]
Hi all ... I had an issue with template execution due to Kubernetes version. template code version is no longer supported.

_"kubernetesVersion": "1.15.10"_ **#No Longer Supported**

I fixed the issue manually validating supported versions for my region and changing the value. But I think this issue can be better solved using a new parameter on the template-parameters file.

**Comment by crpietschmann** [comment]
Thanks for brining this up. The update that is still in progress to the MCW has updated the kubernetes version to 1.15.11 which is a supported version.
