### ISSUE TITLE
kubernetes dashboard 

### ISSUE THREAD

**Issue by r-kalyan-r** [microsoft/MCW-Cloud-native-applications#165]
when i give az aks browse --name fabmedical-SUFFIX --resource-group fabmedical-SUFFIX it is asking for token or config file to login what should i do

**Comment by waltermyersiii** [comment]
Did you create the ClusterRoleBinding step previously?

kubectl create clusterrolebinding kubernetes-dashboard --clusterrole=cluster-admin --serviceaccount=kube-system:kubernetes-dashboard

**Comment by crpietschmann** [comment]
Please be sure to follow all the steps. Skipping the `kubectl create clusterrolebinding` step may prevent it from working.
