### ISSUE TITLE
Getting helm web status failed issue .

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Cloud-native-applications#167]
Getting helm web installation issue exercise 2-->Task 4--> Step 23:- 

please find the below screenshots for refrence:- 
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/45102602/89660953-b2657b80-d8ef-11ea-8a83-c1b14edcc7eb.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/45102602/89660958-b42f3f00-d8ef-11ea-869c-053a9dfaaf58.png)

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #156
