### ISSUE TITLE
azureKubernetes version in azuredeploy.json file

### ISSUE THREAD

**Issue by hans-verbeeck** [microsoft/MCW-Cloud-native-applications#169]
![MCWIssue1](https://user-images.githubusercontent.com/60719831/90228003-c93b2f00-de15-11ea-8bce-45ba1e05e295.JPG)
I had to change the kubernetesVersion from 1.15.10 to 1.15.11before the deployment would start. I work in the regions West Europe, North Europe, West US and West US 2.

**Comment by timahenning** [comment]
@hans-verbeeck We are about to release an update in the next couple of days.

**Comment by hans-verbeeck** [comment]
Great, thank you.

I hope you will be releasing more fixes. I have tried twice to get through the HOL but failed each time early on in the workshop, not long after the pre-reqs…

Thx,
Hans

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #156
