### ISSUE TITLE
AAD Service Principal (Task 5) needs updating

### ISSUE THREAD

**Issue by rwildema** [microsoft/MCW-Cloud-native-applications#170]
It appears our guidance for connecting to AKS with a Service Principal has changed since this lab guide was written. per https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-kubernetes an image pull secret needs to be created and used for Task 2 in the development track of the HOL.     
Please let me know if i can assist in updating and feel free to ping me on Teams

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #156
