### ISSUE TITLE
issues while running pipeline for content-web.

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Cloud-native-applications#171]
In exercise 1 last step while setting up the build for Content-web, the pipeline getting failed with error "docker repository is not found or you need to docker login again " but i am able to run the pipeline for content-api, 

also getting the below issue while committing locally.
![image](https://user-images.githubusercontent.com/45102602/91289733-58e6c300-e7b0-11ea-9777-80bcb3fd4a40.png)

**Comment by DawnmarieDesJardins** [comment]
@sumitmalik51 
Hi Sumit!  I just merged an update PR to the repo.  Please review and let us know if that resolved your issue.

**Comment by sumitmalik51** [comment]
thanks for the update, will reopen the issue if i face again.
