### ISSUE TITLE
kubernates dashboard not working

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Cloud-native-applications#173]
HI in exercise 2 while accesing kubernates dashboard we are facing issue in authentication , we need to get tokens for authentication that is not mentioned in lab guide . we can get that using **kubect config view** . after authentication i am getting an error 200 
![image](https://user-images.githubusercontent.com/57964598/91715761-f7f22d00-ebab-11ea-94c9-ef34250c3830.png)

Note: we are using 1.16.13 version of aks as 1.15 will be no longer supported

**Comment by himanshuahlawat31** [comment]
Hi , any update on this?

**Comment by timahenning** [comment]
Thank you for reporting this issue.  We are working to resolve your issue within the support time frame defined in https://microsoftcloudworkshop.com/.  If you have a workshop delivery coming up soon, leave a comment with details and we will try to resolve the issue sooner.  In the meantime, verify all task instructions have been followed and Azure environment is still valid.

Tim

**Comment by himanshuahlawat31** [comment]
Yes we have lab scheduled for 4-september, if possible can you please prioritise this ?

**Comment by timahenning** [comment]
The content author has not been able to review the issue just yet.  Have you tried this version:  "kubernetesVersion": "1.15.12"?

**Comment by DawnmarieDesJardins** [comment]
@himanshuahlawat31 
Hello,  I received confirmation from our author to update to version 1.15.12.  I just merged that PR, you should be good to go.  Closing issue as resolved.
