### ISSUE TITLE
Before the HOL - Cloud-native applications

### ISSUE THREAD

**Issue by VaibhavCSA** [microsoft/MCW-Cloud-native-applications#181]
Before the HOL - Cloud-native applications - Task 6 Fails 

ValidationError: Azure Error: InvalidTemplate
Message: Deployment template validation failed: 'The template parameters 'Suffix, VirtualMachineAdminUsername, VirtualMachineAdminPassword, VirtualMachineAdminUsernameLinux, VirtualMachineAdminPublicKeyLinux, KubernetesServicePrincipalClientId, KubernetesServicePrincipalClientSecret, KubernetesServicePrincipalObjectId' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'environment, siteName, administratorLogin, administratorLoginPassword, databaseSkuCapacity, databaseSkuName, databaseSkuSizeMB, databaseSkuTier, postgresqlVersion, location, databaseskuFamily'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.
Additional Information:
        Type: TemplateViolation
        Info: {
            "lineNumber": 0,
            "linePosition": 0,
            "path": ""
        }

**Comment by crpietschmann** [comment]
Did you make sure you configured the template parameters in the `azuredeploy.parameters.json` file before running the template deployment?

I have run the template deployment recently and it does work without error.

**Comment by timahenning** [comment]
@VaibhavCSA Did you get a chance to try Chris's suggestion?

**Comment by VaibhavCSA** [comment]
Hello Tim,
It was a long weekend here in AUS, I am back on decks will try it update you guys.

Thanks a Ton !

With Gratitude.
Vaibhav
Cloud Solution Architect (Apps & Infra)
[cid:948a1dd7-67c7-4721-9a7d-3a950d2e1273]
________________________________

**Comment by DawnmarieDesJardins** [comment]
No additional input, closing issue.
