### ISSUE TITLE
Helm chart for cert manager needs update in exercise 4 task 5

### ISSUE THREAD

**Issue by waeltken** [microsoft/MCW-Cloud-native-applications#182]
The cert manager version 0.8 used in the hands on lab is not compatible with kubernetes 1.17 and needs an update.

Caused by the deprecation of `apps/v1beta1` in the newer k8s version.
Please watch out that later versions of cert manager change the API for `ClusterIssuer`.

https://github.com/jetstack/cert-manager/blob/release-0.8/deploy/charts/cert-manager/templates/deployment.yaml

**Comment by timahenning** [comment]
Fixed in recent update.
