### ISSUE TITLE
Issues with AKS version 1.17.10

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Cloud-native-applications#183]
The cert manager version 0.8 used in the hands on lab is not compatible with kubernetes 1.17 and needs an update.

Caused by the deprecation of apps/v1beta1 in the newer k8s version.

* Exercise 2 task 2 step 3 CPU is not accepting 0.125
![1](https://user-images.githubusercontent.com/45102602/94393511-d2d7e680-0178-11eb-8a6b-93ea8050cda7.jpg)

* provided 1 at place of 0.125 but the is shown below error
![2](https://user-images.githubusercontent.com/45102602/94393543-e6834d00-0178-11eb-8685-2fc4f66e0d37.jpg)

**Comment by akn9050** [comment]
Hi @timahenning, when are you merging the fixes. We gave to try out the fixes for upcoming scheduled labs.

**Comment by timahenning** [comment]
@akn9050 The technical fixes were merged to master.  The small markdown changes will be published later.
