### ISSUE TITLE
October 2020 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Cloud-native-applications#188]
### Pull Requests to be Assessed and pulled in appropriately
- [x] PR #186 Revert "Update template to use System Assigned Identity."
- [x] PR #187 Update containerRegistry env in sample yaml

### Design Session Additions

- [x] Add relational vs non-relational component to the design session

  - Relational database will focus on PostgreSQL on Azure

  - Will keep the Speakers and Sessions list being stored in Cosmos DB (as-is today)

  - Will add Attendee and Session Feedback / Comment data that is relational, so it’ll be stored in PostgreSQL

     - To make this fit the scenario, the requirements for the Conference website will be modified to add the ability for registered attendees to post comments / feedback thread on the Sessions for increases community interaction related to the conference.

- [x] Add AI / Cognitive Services to the design session

  - Content moderator functionality will be added to the scenario for the Session comment / feedback functionality. This will incorporate the following components

  - Comments are passed to the Cognitive Services Content Moderator API to ensure inappropriate content is not allowed to be posted by attendees.

  - Language Translator Cognitive Services API will be used to support real-time text translation of attendee posted content so it can be displayed to other attendees in their preferred language

_NOTE: It’s worth noting that the Intelligent Analytics MCW also incorporates Cognitive Services Sentiment Analytics._

### Hands-on Labs Updates _(in both Dev and Infra lab guides)_

Within my below estimates of the proposed lab changes/additions, we’ve added estimates on the amount of lab duration change for each lab addition/change. We'll update the lab exercise time estimates in the lab when changes are made.

- [x] Update npm packages in sample app

- [x] Exercise 1, Task 7: Run several containers with Docker compose
  _Lab Time Change: Decrease lab duration by 10 minutes_

  - This Task will be removed.

- [x] Exercise 2, Task 5: Initialize database with a Kubernetes Job
  _Lab Time Change: Increase lab duration by 20 minutes_

  - Add a new Exercise to perform migration from MongoDB to Cosmos DB using Azure Database Migration Service

- [x] Exercise 3, Task 2: Increase service instances beyond available resources
  _Lab Time Change: Increase lab duration by 20 minutes_

  - [x] Add configuration change to Cosmos DB to go from 400 RU/s to setup Autoscale

  - [x] Add steps to see the Autoscale enabled is allowing greater performance than 400 RU/s

  - [x] Add code to saturate the 400 RU/s so when Cosmos DB is updated to Autoscale configurations, it can be seen that the autoscale kicks in.

- [x] Exercise 3, Task 3: Restart containers and test HA
  _Lab Time Change: Increase lab duration by 30 minutes_

  - [x] configure Traffic Manager for load balancing
  - ~~Add a new Exercise to deploy AKS in a secondary Azure region.~~ _(removed as it would add to much time to lab with duplicate steps anyway_)

**Comment by DawnmarieDesJardins** [comment]
Feedback received via email:

From: Cameron Sipes 
Subject: RE: Cloud-native application - Content update confirmation

Hi Team,

I went through the proposed changes in the below GitHub repo for updating the Cloud Native In-A-Day/Azure Immersion Workshop and it looks to align to our feedback.

Thanks,
Cameron

From: Maddy Butzbach 
Subject: RE: Cloud-native application - Content update confirmation

This looks great to me on cog services and Postgres – thanks!

**Comment by snpdev** [comment]
As a trainer that delivers the Cloud Native in a Day workshop, I'd like to make a few comments about the October update.

I like the suggestions for Exercise 3, but in the workshop we'll never get that far. 

The timings given for each exercise are way off. In my last virtual delivery, we stepped though the developer HOL and after 3.5 hours, only made it through [Exercise 2, Task 6](https://github.com/microsoft/MCW-Cloud-native-applications/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Cloud-native%20applications%20-%20Developer%20edition.md#task-6-test-the-application-in-a-browser).

That said, I had positive feedback from users about [Task 7: Run several containers with Docker compose](https://github.com/microsoft/MCW-Cloud-native-applications/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Cloud-native%20applications%20-%20Developer%20edition.md#task-7-run-several-containers-with-docker-compose). Docker compose is an important tool for local development. If the motivation for removing this task is to shave time off the HOL, it does not save much time. There are other ways to compress the lab.

On that note, I have some other comments about the HOL for which I'll create issues. Thanks for listening :smiley:

**Comment by crpietschmann** [comment]
For the Traffic Manager piece, I'm leaving off creating another AKS in a secondary region. Doing this would repeat many steps at the beginning of the lab and add like another hour to it's length. Setting up Traffic Manager with the one AKS will show the steps necessary, and introduce attendees to what they would do to have a multi-region AKS environment using Traffic Manager.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #205
