### ISSUE TITLE
exercise 2 task 2 step 16 

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Cloud-native-applications#195]
Hi , while deploying apideployment.yml i am facing the following error 
![image](https://user-images.githubusercontent.com/57964598/97934125-c27be280-1d9a-11eb-8ccf-8b7d2b3f0e88.png)

I have checked the indendation in yml it is as per lab guide , still i am facing this issue .

can you please take a look into this?

**Comment by himanshuahlawat31** [comment]
when we use kubernates dashboard sometimes we get the following error 
![image](https://user-images.githubusercontent.com/57964598/97934454-c8be8e80-1d9b-11eb-8e05-cf4fd0b8d31f.png)

**Comment by saimachi** [comment]
Hello @himanshuahlawat31,

Unfortunately, we were not able to isolate the same issue that you encountered. Moreover, this warning message is unclear, as mentioned in https://github.com/kubernetes/kubernetes/issues/82154. You could run _kubectl get all_ or _kubectl rollout status deployment.apps/api_ in the Azure cloud shell. The second command demonstrates whether the pod replicas of the deployment are properly rolled out. Let us know what you see. 

Note that if you deploy to Kubernetes, and then try to update the deployment, you will need to use the _kubectl patch_ command. You can find more information about that at https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/.

**Comment by timahenning** [comment]
Hi @himanshuahlawat31,

Is there any other discussion on this issue?  If not, I will close this issue in a few days.

**Comment by crpietschmann** [comment]
@himanshuahlawat31 On the error mentioned when using the Kubernetes Dashboard, there is a bug of some kind in the Kubernetes Dashboard (`kubernetes-dashboard`) that is causing an authentication issue some times when accessing the dashboard web app through a proxy how it's used in AKS. All you need to do is click the "user/profile" icon in the upper-right of the dashboard, select "Sign out", then sign back into the K8s dashboard and it'll work again. Here's a little more info about this: <https://build5nines.com/fix-kubernetes-dashboard-strange-401-unauthorized-503-service-unavailable-errors/>

For the other issue, do you have anything else in regards to the above followup on it?

**Comment by himanshuahlawat31** [comment]
Hi , we tried the lab again and found same issue , we found a workaround that if we deploy existing app from dashboard and then try to deploy using command it will work

**Comment by akn9050** [comment]
Hi @crpietschmann, I tested out the lab and found that the deployment configuration which we are downloading in ex2, task2 step 16 for the api which was created using UI, after downloading we are are adding Image property in deployment configuration file and then applying those in teh same api in step 19 using ```kubectl apply -f api.deployment.yml``` , which is not working as api created from UI is not supporting the changes made from command line.

I had to delete the API from UI and then created the API again from command line with updated deployment configuration file, which worked fine.

**Comment by timahenning** [comment]
It sounds like your issue has been resolved.
