### ISSUE TITLE
Kubernetes Dashboard deprecation?

### ISSUE THREAD

**Issue by snpdev** [microsoft/MCW-Cloud-native-applications#196]
Much of [Exercise 2: Deploy the solution to Azure Kubernetes Service](https://github.com/microsoft/MCW-Cloud-native-applications/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Cloud-native%20applications%20-%20Developer%20edition.md#exercise-2-deploy-the-solution-to-azure-kubernetes-service) revolves around the use of the Kubernetes management dashboard. This leaves the impression that the dashboard is the go-to place for AKS workload management and monitoring. Perhaps I am misunderstanding, but I thought that the dashboard is being deprecated in AKS. Per [https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard](https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard),

> Starting with Kubernetes 1.19 in preview, AKS will no longer support installation of the managed kube-dashboard addon.

**Comment by crpietschmann** [comment]
Yes, as you noted the Kubernetes resource view (currently in preview) in the Azure Portal is the replacement Microsoft is providing as they will be deprecating the Kube Dashboard on K8s 1.19 (currently in preview) and higher. The lab is currently built using K8s 1.17.11 which does support the Kubernetes Dashboard in AKS, so the lab steps as written are currently functional and supported by Microsoft on AKS.

As we update this MCW lab to K8s 1.19 in a future update, we will need to rework the lab steps to use the Kubernetes resource view within the Azure Portal instead fo the Kubernetes Dashboard. These changes will need to wait for a future MCW update cycle to be worked on.

Thanks for the suggestions on improving the lab in the future. :)

**Comment by snpdev** [comment]
Thanks @crpietschmann. Frankly, I am not keen on training people on soon to be deprecated tech. I'll at least warn people, show them kubectl cli alternatives, and as time allows dip into the Kubernetes resource view.

I'm scheduled to deliver the workshop again in January and March 2021. When the time comes, I'll need to coordinate with the Microsoft partner that provisions the labs to ensure they are not running K8s 1.19.x.

**Comment by crpietschmann** [comment]
Update: I've done some exploration of the "Kubernetes resource view" preview features in the Azure Portal, and it doesn't have all the same feature parity of the Kubernetes Dashboard just yet. I don't know when it'll be GA, but I'd assume it'll have more functionality by that time.

**Comment by snpdev** [comment]
I believe you are right @crpietschmann. 

At the moment, I am inclined to skip over Tasks 1 & 2 of Exercise 2 and go straight to [Task 3: Deploy a service using kubectl](https://github.com/microsoft/MCW-Cloud-native-applications/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Cloud-native%20applications%20-%20Developer%20edition.md#task-3-deploy-a-service-using-kubectl).

In any event, please let me know when the update is ready for a test drive. I'd be happy to review the update branch before it's merged to master. Thanks!

**Comment by DawnmarieDesJardins** [comment]
@snpdev 
Thanks Mike!  I'm the PM for the MCWs.  I've added your name to my SME list for our next update.  Closing this issue for now as there is no available action.

**Comment by snpdev** [comment]
Today, I received an email from Microsoft saying:

> Starting on 31 March 2021, you'll no longer be able to create new clusters using Kubernetes 1.17.x. 

According to https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard:

> The dashboard add-on will be disabled by default for all new clusters created on Kubernetes 1.18 or greater.

I am running a workshop on April 22nd. Do I need to be concerned?
