### ISSUE TITLE
clone local git to azure devops error

### ISSUE THREAD

**Issue by rajredd** [microsoft/MCW-Cloud-native-applications#200]
error: failed to push some refs to 'https://rajredd@dev.azure.com/rajredd/fabmedical/_git/content-web'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

after this command : git push -u origin --all 

seems like the README.md file on the remote site (azure devops) is different from the one on the local site.

**Comment by timahenning** [comment]
Hi @rajredd,

Does your remote origin repo have updates that need to be merged locally?  Try a 'git fetch'.   What HOL were you working on when you received this message?  What exercise and task were you on when you received this error message?

**Comment by rajredd** [comment]
THANKS FOR REPLY.  THE ERROR CAME AFTER STEP 21 FROM THE ATTACHED INSTRUCTIONS. 
    On Thursday, November 12, 2020, 02:11:16 PM EST, Tim Henning <notifications@github.com> wrote:  
 
 


Hi @rajredd,

Does your remote origin repo have updates that need to be merged locally? Try a 'git fetch'. What HOL were you working on when you received this message? What exercise and task were you on when you received this error message?

**Comment by timahenning** [comment]
Hi @rajredd,

Did you see my Git question?

**Comment by rajredd** [comment]
>> Does your remote origin repo have updates that need to be merged locally? 

I followed the steps 18-19 from "before the HOL" pdf file; and there was README.md file generated from the step 18 (create a new repository).  there was no updates on this remote origin repo other than this README.md file.

**Comment by rajredd** [comment]
I sent the following commands in azure cli,

rajred@Azure:~/MCW-Cloud-native-applications/Hands-on lab/lab-files/infrastructure/content-web$ **git fetch**
Password for 'https://rajred@dev.azure.com':
warning: no common commits
remote: Azure Repos
remote: We noticed you're using an older version of Git. For the best experience, upgrade to a newer version.
remote: Found 3 objects to send. (31 ms)
Unpacking objects: 100% (3/3), done.
From https://dev.azure.com/rajred/fabmedical/_git/content-web
 + cf93b65...520cb28 master     -> origin/master  (forced update)
rajred@Azure:~/MCW-Cloud-native-applications/Hands-on lab/lab-files/infrastructure/content-web$ git remote add origin https://rajred@dev.azure.com/rajred/fabmedical/_git/content-web
fatal: remote origin already exists.
rajred@Azure:~/MCW-Cloud-native-applications/Hands-on lab/lab-files/infrastructure/content-web$ git push -u origin --all
To https://rajred@dev.azure.com/rajred/fabmedical/_git/content-web
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://rajred@dev.azure.com/rajred/fabmedical/_git/content-web'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by timahenning** [comment]
You should not have a readme.md file in your repo.  The before hands on lab has this instruction:

![image](https://user-images.githubusercontent.com/48766586/99082062-8570d680-2578-11eb-92e0-c6d12aee863a.png)

Try 'git pull' to merge the remote repo with your local repo.

**Comment by rajredd** [comment]
yes, it worked now. I deleted/recreated "content-web" repository without README.md. PHEW !

**Comment by rajredd** [comment]
thank you very much. 
    On Friday, November 13, 2020, 09:23:36 AM EST, Tim Henning <notifications@github.com> wrote:  
 
 


You should not have a readme.md file in your repo. The before hands on lab has this instruction:



Try 'git pull' to merge the remote repo with your local repo.
