### ISSUE TITLE
ng build not working? 

### ISSUE THREAD

**Issue by rajredd** [microsoft/MCW-Cloud-native-applications#201]
having issue when execute task1/step 13 from "HOL step-by-step" instructions. (see below)
=========
13. Navigate to the web application directory, run npm install and ng build.

cd ../content-web
npm install
ng build      <==     having issue
====

rajredafabmedical@fabmedical-887:~/content-web$ ng build
The program 'ng' is currently not installed. You can install it by typing:
sudo apt install ng-common

====
I went ahead to execute "sudo apt install ng-common" and reran "ng build"; what I got was something like entering an editing mode to create a file. (not sure what that was)
could not continue...

**Comment by timahenning** [comment]
Hi @rajredd,

In the Before HOL, there is a step to install the Angular CLI.

![image](https://user-images.githubusercontent.com/48766586/99100121-38006380-2590-11eb-84ae-bf9b5b99fc8c.png)

Execute that step and you should be fine.

**Comment by rajredd** [comment]
I do remember I have done "sudo npm install -g @angular/cli" before run HOL step-by-step. I went back to agent build VM, reinstall agaular/cli, I was able to build app.js now. thanks. I am able to see all the speakers and sessions data from VM public ip address now. thanks.
