### ISSUE TITLE
could not locate 'Settings' tab from GitHub repository

### ISSUE THREAD

**Issue by rajredd** [microsoft/MCW-Cloud-native-applications#202]
Exercise 1/Task 8
====
Task 8: Setup CI Pipeline to Push Images
In this task, you will use YAML to define a GitHub Actions workflow that builds your Docker image and pushes it to your ACR instance automatically.

In GitHub, return to the Fabmedical repository screen, and select the Settings tab. <== could not find this tab
====

I did not find "Settings tab" (after "Insights" tab)  from GitHub repository - (https://github.com/microsoft/MCW-Cloud-native-applications) under my login account. Am I looking at the wrong url?

**Comment by rajredd** [comment]
I tried to append "/settings" to the url, it did not work.  

http://blog.ericd.net/2020/01/17/github-i-lost-my-repo-settings-tab/

**Comment by timahenning** [comment]
Hi @rajredd,

I found the task information you referenced in Task 9.

![image](https://user-images.githubusercontent.com/48766586/99148115-cd583200-263a-11eb-9bf5-52029bd6ccfb.png)

![image](https://user-images.githubusercontent.com/48766586/99148163-1a3c0880-263b-11eb-9e94-aa7cff75603c.png)

**Comment by rajredd** [comment]
I found the Setting tab after I forked my own copy of this workshop repository. thanks.
