### ISSUE TITLE
Wrong command in Exercise 1, Task 1, Step 14

### ISSUE THREAD

**Issue by immeorfj** [microsoft/MCW-Cloud-native-applications#206]
The provisioned VM is just named fabmedical and not fabmedical-[SHORT_SUFFIX]

This means that the command
`az vm show -d -g fabmedical-[SUFFIX] -n fabmedical-[SHORT_SUFFIX] --query publicIps -o tsv` 

should be changed to

`az vm show -d -g fabmedical-[SUFFIX] -n fabmedical --query publicIps -o tsv`

**Comment by saimachi** [comment]
Hello @immeorfj,

Unfortunately, we were not able to encounter the same problem. When you deploy the ARM template mentioned in the Before the Hands-on Lab document, you need to configure deployment parameters in the _azuredeploy.parameters.json_ file (Task 6). In this case, you need to provide a three-letter suffix.

Also note that this lab is undergoing review. If you continue to encounter problems, follow the updated instructions in the update-oct-2020 branch (https://github.com/microsoft/MCW-Cloud-native-applications/tree/update-oct-2020).

**Comment by timahenning** [comment]
Hi,

We have not heard any feedback from the field.  We will be happy to open the issue if needed.
