### ISSUE TITLE
"ng build" error in

### ISSUE THREAD

**Issue by wely** [microsoft/MCW-Cloud-native-applications#207]
Hi folks,
HOL-Developer Edition: Exercise 1, Task 1, Step 13 after running "ng build"
Apparently it doesn't work as expected.
![image](https://user-images.githubusercontent.com/1658657/100431661-74c17400-30d3-11eb-9e6a-5a55eeb3f128.png)

**Comment by sajeetharan** [comment]
It worked fine for me! can you paste a screen shot? here is mine,

![image](https://user-images.githubusercontent.com/4833351/100456578-a5f76f80-30e6-11eb-9858-7afd988f70e2.png)

**Comment by saimachi** [comment]
Hi @wely,

We were unable to isolate the same problem. Ensure that you are in the _~/Fabmedical/content-web_ directory when you run the command. Moreover, the command is _ng build_, but it appears that you may have accidentally opened a text editor in your cloud shell, so please verify that you entered all commands properly. When you run the command properly, you should see something similar to what @sajeetharan has.

Let us know if you run into any other problems. If you do, provide us with a screenshot listing which errors you receive and the contents of your current directory.

**Comment by wely** [comment]
thanks @sajeetharan and @saimachi 
It's fine now. the issue was i copied / pasted multiple lines at one time to the command prompt :)
