### ISSUE TITLE
Issue in developer edition 

### ISSUE THREAD

**Issue by anushabc** [microsoft/MCW-Cloud-native-applications#210]
- Exercise 1, Task 5,  step 4 screenshot shows we are executing the commands from the content-web folder but there is no instruction that tells us to navigate to the content-web folder.

- Exercise 1, Task 7, Step 11 says Repeat Step 7 to push the images to ACR again so that the newly tagged v1 images are pushed. But when we run the command it is not pushing v1 instead it's pushing the latest.  However, images with tag v1 were pushed with the below commands.

  docker image push [LOGINSERVER]/content-web:v1
  docker image push [LOGINSERVER]/content-api:v1
  docker image push [LOGINSERVER]/content-init:v1

-  Exercise 1 Task 8, step 9 has a spacing issue in content-web due to which workflow was failing. Attaching the file with correct format 

    [content-web.txt](https://github.com/microsoft/MCW-Cloud-native-applications/files/5714909/content-web.txt)

- Exercise 4, Task 1, didn't work for me, it says insufficient cpu.
 
    
   ![ex4](https://user-images.githubusercontent.com/66515706/102969756-455c2680-451c-11eb-8170-f9349206f506.png)

- Exercise 5, Task 3, even after increasing cpu to 125m it failed with error invalid syntax and insufficient cpu.

  
  ![ex5](https://user-images.githubusercontent.com/66515706/102970072-dcc17980-451c-11eb-89b1-338ae3b757ed.png)

**Comment by akn9050** [comment]
Hi @crpietschmann , @timahenning did you get chance to review these.

**Comment by timahenning** [comment]
Hi @akn9050, We are looking into it today.

**Comment by crpietschmann** [comment]
- Exercise 1, Task 5, step 4: Previously in the guide, it instructs to you to navigate between the different code directories, so at this point in the guide it assumes you know what/how to do it.
- Exercise 1, Task 7, Step 11: A fix for this has been committed.
- Exercise 1 Task 8, step 9: This can happen when copying and pasting from the HTML view some times. If you copy/paste from the Markdown, you shouldn't have an issue.
- Exercise 4, Task 1: Going through Exercise 4 the guide takes you through this on purpose as part of the exercise.
- Exercise 5, Task 3: Try rechecking the steps previously in Exercise 5. When followed as written, there shouldn't be an error here.

**Comment by akn9050** [comment]
Hi @crpietschmann, it would help lab attendees and whoever do the lab if we can add a note for Exercise 4, Task 1: Like insufficient cpu error is expected. It is no where showed if this is expected or not, so most of the folks stuck here and don't proceed further with lab.

**Comment by timahenning** [comment]
@akn9050 That is a good idea.  We will try add that this week.

Tim

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved.  All points address and additional notes added to docs with merge of PR #213 .
