### ISSUE TITLE
Before the HOL Task 6 Issue

### ISSUE THREAD

**Issue by snpdev** [microsoft/MCW-Cloud-native-applications#211]
Step 6 of [Task 3](https://github.com/microsoft/MCW-Cloud-native-applications/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Cloud-native%20applications.md#task-5-create-a-service-principal) asks to update the values for the keys below in the file `azuredeploy.parameters.json`. However, these keys are not present in the file.

- **KubernetesServicePrincipalClientId**: The Kubernetes Cluster Service Principal Client Id. Use the service principal appId from a previous step.
- **KubernetesServicePrincipalClientSecret**: The Kubernetes Cluster Service Principal Client Secret. Use the service principal password from a previous step.
- **KubernetesServicePrincipalObjectId**: The Kubernetes Cluster Service Principal Object Id. Use the service principal objectId from a previous step.

**Comment by crpietschmann** [comment]
These parameters were removed from the ARM Template, so they aren't set anymore. I have updated the Before HOL guide to no longer include instructions for these parameters that no longer exist in the ARM Template. Thanks!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with latest commit.
