### ISSUE TITLE
Before the HOL Task 9 - Is Docker compose needed?

### ISSUE THREAD

**Issue by snpdev** [microsoft/MCW-Cloud-native-applications#212]
Step 7 of [Task 9](https://github.com/microsoft/MCW-Cloud-native-applications/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Cloud-native%20applications.md#task-9-complete-the-build-agent-setup) asks to Install `docker-compose`.

While not a big deal, since Docker compose is not used in the HOL, perhaps this step should be removed.

**Comment by DawnmarieDesJardins** [comment]
Side note:  Please review ReadMe page, Products and Services for accuracy.

**Comment by crpietschmann** [comment]
Correct, the steps that used Docker Compose were removed in the previous update to the lab. I have committed an update that removes the docker-compose install from the Before HOL steps. Thanks!

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with latest commit.
