### ISSUE TITLE
Obsolete data load instructions

### ISSUE THREAD

**Issue by snpdev** [microsoft/MCW-Cloud-native-applications#215]
Since data from MongoDB is loaded to Cosmos DB using DMS in Exercise 2, the following instructions are obsolete:

**Exercise 3 | Task 3 | Step 14**

> Note that no data is displayed, although we have connected to our Cosmos DB instance, there is no data loaded. You will resolve this by running the content-init application as a Kubernetes Job in Task 5.

**Exercise 3 | Task 4 | Step 25**

> Note that no data is displayed, although we have connected to our Cosmos DB instance, there is no data loaded. You will resolve this by running the content-init application as a Kubernetes Job.

**Comment by crpietschmann** [comment]
Yes this is correct. I have submitted PR #219 that removes these instructions that are no longer accurate.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #219
