### ISSUE TITLE
Suggestion: Remove content-init containerization

### ISSUE THREAD

**Issue by snpdev** [microsoft/MCW-Cloud-native-applications#216]
With the recent DMS addition to the lab ([Exercise 2](https://github.com/microsoft/MCW-Cloud-native-applications/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Cloud-native%20applications%20-%20Developer%20edition.md#exercise-2-migrate-mongodb-to-cosmos-db-using-azure-database-migration-service)), the `content-init` container has no further utility.

Unless I am misunderstanding, there is no need to create a container image for the `content-init` code since it won't be used later. Removing the image build and related ACR deployment and GitHub Action will shave valuable time off the lab, particularly important in a partner delivered workshop setting.

**Comment by crpietschmann** [comment]
I submitted PR #220 that removes the steps to create the `content-init` GitHub Action as well as pushing the `content-init` container to ACR. You are correct that these are no longer necessary in the lab.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #220
