### ISSUE TITLE
Kubernetes version is not supported in this region

### ISSUE THREAD

**Issue by fatihdurgut** [microsoft/MCW-Cloud-native-applications#218]
Before the HOL Instruction -> When you try to run ARM template you got following error. 

afatihdurgut@Azure:~/MCW-Cloud-native-applications/Hands-on lab/arm$ az deployment group create --resource-group fabmedical-sol --template-file azuredeploy.json --parameters azuredeploy.parameters.json

{"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'azuredeploy' is not valid according to the validationprocedure. The tracking id is '98bb83ae-b73c-4393-bd8e-c4c1a7456b9c'. See inner errors for details.","details":[{"code":"AgentPoolK8sVersionNotSupported","message":"Provisioning of resource(s) for container service fabmedical-sol in resource group fabmedical-sol failed. Message: {\n  \"code\": \"AgentPoolK8sVersionNotSupported\",\n  \"message\": \"Version 1.17.11 is not supported in this region. Please use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list\"\n }. Details: "}]}}

**Comment by kareldewinter** [comment]
There will be another problem if you go for a higher Kubernetes version. The Kubernetes dashboard will not be available anymore. The problem will be in exercise 3 -> Task 2: "Deploy a service using the Kubernetes management dashboard".

Info:
The Kubernetes dashboard is enabled by default for clusters running a Kubernetes version **less than** 1.18.
The dashboard add-on will be **disabled** by default for all new clusters created on **Kubernetes 1.18** or greater.

**Comment by crpietschmann** [comment]
I submitted PR #225 that addresses this for the short term. It updates the Kubernetes version to 1.17.16 which is the latest supported 1.17.x release by AKS. This will fix the deployment for now.

However, as you pointed out for v1.18 and higher, we will need to modify the MCW in the next update cycle to use a more recent point release and move away from the K8s Dashboard as well.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #225
