### ISSUE TITLE
Content-web app.js wrong instruction

### ISSUE THREAD

**Issue by fatihdurgut** [microsoft/MCW-Cloud-native-applications#221]
Exercise 1: Create and run a Docker application --> Task 1 --> Item 15

From the cloud shell in the build machine edit the app.js file using vim.
Then press i to get into the edit mode, after that replace localhost with the build machine IP address.
Edit the app.js file in vim in the build machine to update the API URL.

Exercise 1: Create and run a Docker application --> Task 5 --> Item 4
Observe that the contentApiUrl variable can be set with an environment variable.
const contentApiUrl = process.env.CONTENT_API_URL || "http://localhost:3001";

Issue: The URL is not localhost anymore since we changed it in Item15.

**Comment by crpietschmann** [comment]
If you follow the lab steps as written it does work. Ex 1, Task 4, Item 4, is using localhost because when content-web runs it will be able to access the content-api on port 3001 on localhost since they are both running on the same machine.

**Comment by timahenning** [comment]
We have not heard any feedback from the field.  We will be happy to open the issue if needed.
