### ISSUE TITLE
Error in Migrate MongoDB to Cosmos DB

### ISSUE THREAD

**Issue by fatihdurgut** [microsoft/MCW-Cloud-native-applications#222]
Exercise 2: Migrate MongoDB to Cosmos DB using Azure Database Migration Service --> Task 3 --> Item 5 is not working due to network rules of the Build Agent VM. Wizard could not connect the mongodb. 
To fix--> You need to give "Allow access to port 27017" on Networking tab of the build agent vm.

**Comment by saimachi** [comment]
Hi @fatihdurgut,

I was unable to reproduce the same error. Ensure that you are referencing your build agent VM private IP address within DMS, not its public IP. When you provisioned DMS in Exercise 2, Task 2, you provisioned it on your resource group's virtual network. This allows DMS to communicate with the VM using private IP addresses. In the _Networking_ tab of the VM, you can see that inbound traffic from any location on the VM's VNet is permitted.

![dms-on-vnet](https://user-images.githubusercontent.com/37318129/106237094-ea6cbd80-61b2-11eb-82af-554f3d3732d0.png)

**Comment by saimachi** [comment]
@fatihdurgut Let us know if you continue to face problems enabling communication between MongoDB and DMS.

**Comment by zekink** [comment]
I also ran into an issue trying to run the migration to Cosmos DB - I should have checked the GitHub issues to see if this solution would have helped me. Here's a screenshot of what made me unable to progress for reference.
![Screenshot 2021-03-25 at 17 49 25](https://user-images.githubusercontent.com/13997056/112514692-3d6f8500-8d9e-11eb-807d-ad0caf365bc2.png)
