### ISSUE TITLE
Missing docker image tag command

### ISSUE THREAD

**Issue by kareldewinter** [microsoft/MCW-Cloud-native-applications#223]
In Exercise 1 -> Task 6: Push images to Azure Container Registry -> Step 10
Missing docker image tag command for content-init, only content-web and content-api are defined.

Solution:
docker image tag [LOGINSERVER]/content-web:latest [LOGINSERVER]/content-web:v1
docker image tag [LOGINSERVER]/content-api:latest [LOGINSERVER]/content-api:v1
docker image tag [LOGINSERVER]/content-init:latest [LOGINSERVER]/content-init:v1
docker image ls

**Comment by snpdev** [comment]
@kareldewinter , please refer to #216.

**Comment by crpietschmann** [comment]
Correct, this was removed as the docker image tag command steps are no longer needed for content-init after the mongodb migration to cosmosdb steps were modified in a previous update.

**Comment by timahenning** [comment]
Closing the issue.  Solution provided.  We will be happy to reopen the issue if needed.
