### ISSUE TITLE
Typo error 

### ISSUE THREAD

**Issue by fatihdurgut** [microsoft/MCW-Cloud-native-applications#224]
In the infrastructure HOL 

Task 6: Configure Continuous Delivery to the Kubernetes Cluster

Navigate to the .github/workflows folder of the git repository, and open the content-web.yml workflow using vi:

cd ~/MCW-Cloud-native-applications/Hands-on\ lab/lab-files/**_developer_**/.github/workflows
vi content-web.yml

The above command should be 

cd ~/MCW-Cloud-native-applications/Hands-on\ lab/lab-files/**_Infrastructure_**/.github/workflows

**Comment by saimachi** [comment]
Hello @fatihdurgut,

Thank you for highlighting this issue of referencing the incorrect GitHub Actions workflow configuration files. We have resolved it with #227.
