### ISSUE TITLE
Update HOL to use Kubernetes resource in Azure Portal

### ISSUE THREAD

**Issue by tomkerkhove** [microsoft/MCW-Cloud-native-applications#236]
Update HOL to use Kubernetes resource in Azure Portal instead of Kubernetes Dashboard which will no longer be added to AKS clusters (v1.19 and above, see https://github.com/azure-deprecation/dashboard/issues/121)

https://docs.microsoft.com/en-us/azure/aks/kubernetes-portal

**Comment by timahenning** [comment]
Hi @tomkerkhove,

Thank you for the issue submission.  We are currently working on a small lab update as speak.  Unfortunately, the current lab was written to work with v1.17 and upgrading the lab to work with 1.19 is not planned at the moment.  The lab is being deprecated by 6/1/21.  Please refer to Microsoft Learn for AKS lab content.

Tim

**Comment by tomkerkhove** [comment]
So Microsoft Learn for AKS lab content is the way forward if I understand it correctly?

**Comment by timahenning** [comment]
At moment, you are correct.
