### ISSUE TITLE
Kubernetes Dashboard deprecation

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Cloud-native-applications#237]
@snpdev @timahenning @crpietschmann 

Hello!  
This comment was added to closed issue #196 today.  I'm creating a new issue so it's on the open issues page and can be addressed.

![image](https://user-images.githubusercontent.com/39317565/111384859-3a221e00-8667-11eb-840d-141bdf3a08fc.png)

**Comment by snpdev** [comment]
Just noticed a related closed issue #236

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #241
