### ISSUE TITLE
Issue in Exercise 5 Task 5

### ISSUE THREAD

**Issue by anushabc** [microsoft/MCW-Cloud-native-applications#245]
- In exercise 5 task 5 step 19 gives an error message

error parsing content.ingress.yml: error converting YAML to JSON: yaml: line 14: did not find expected '-' indicator

-  Exercise 5 task 6 still not able to access the Contoso application from the traffic manager.

Contoso application  is accessible from ingress endpoint

![image](https://user-images.githubusercontent.com/66515706/113120777-907a8980-922f-11eb-9849-ecdb34a85550.png)

But gives this error  when accessed from the traffic manager

![image](https://user-images.githubusercontent.com/66515706/113120642-6f199d80-922f-11eb-8a1e-fb8cbd713a98.png)

**Comment by saimachi** [comment]
Hi @anushabc,

I've started a review of the lab for Chris' changes. I'll study the issue.

**Comment by anushabc** [comment]
Thank you @saimachi, can you also please have a look at exercise4 task 1,   after increasing the replica count to 2 all the pods were showing as healthy but if I increase the replica count to 3 I was able to see one pod in pending state.
![image](https://user-images.githubusercontent.com/66515706/113542469-fa18e000-9601-11eb-9280-41f2e4d804e7.png)

**Comment by saimachi** [comment]
Hi @anushabc,

I cannot confirm what you are describing for Exercise 4, Task 1. Only 1 out of the requested 2 pods provisioned in my environment. The barriers preventing the api deployment from scaling are the CPU constraints and the port constraints, which are remedied in Exercise 4, Task 2. Can you ensure that your api deployment has been configured correctly, as described in Exercise 3, Task 2, Step 5?

Here is an image of the correct state of the api deployment's pods after successfully completing Exercise 4, Task 1:

![image](https://user-images.githubusercontent.com/37318129/113590694-cd57cf00-95e7-11eb-88ca-f07e165db48c.png)

**Comment by timahenning** [comment]
> Thank you @saimachi, can you also please have a look at exercise4 task 1, after increasing the replica count to 2 all the pods were showing as healthy but if I increase the replica count to 3 I was able to see one pod in pending state.
> ![image](https://user-images.githubusercontent.com/66515706/113542469-fa18e000-9601-11eb-9280-41f2e4d804e7.png)

Please reference one issue at a time in a GitHub issue.

Thanks
