### ISSUE TITLE
May 2021 Update

### ISSUE THREAD

**Issue by crpietschmann** [microsoft/MCW-Cloud-native-applications#247]
These are the items to work on for the May 2021 Update:

- [x] Remove "Exercise 1: Create and run a Docker application"
   - Some of these tasks are necessary for the lab to work, so we'll need to simplify them as much as possible, and probably more them to the "Before the HOL". The point of this change is to not have a focus on running Docker locally anymore, and to have the images in ACR ready to go for the rest of the lab.
   - Yes, the MongoDB database population will still need to be done, as this is necessary for the Cosmos DB migration, but again probably ok to put the minimum steps necessary to do this in the "Before the HOL"
- [x] Remove tasks working with Helm, no longer an emphasis in the lab.
- [x] Remove "Task 6: Multi-region Load Balancing with Traffic Manager", no longer an emphasis in the lab.

Also, overall, the K8s tasks should use `kubectl` and Azure Portal AKS UI. The previous fix to the lab did this already, but if there are any wording remnants left, please remove/fix those.

FYI, one of the main goals of removing these items is to shorten the lab time, while still maintaining focus on the core tenants of the MCW. Please reference this modified lab outline as direction to the changes needed: https://github.com/microsoft/MCW-Cloud-native-applications/pull/238/files

**Comment by DawnmarieDesJardins** [comment]
@crpietschmann @timahenning 
Please review comment on closed issue #231 
Not sure if it will apply to changes you're making now or not.

**Comment by crpietschmann** [comment]
@DawnmarieDesJardins @timahenning Installing from NPM take as long as it takes. I've never been able to duplicate the issue of installation taking too long. There's nothing we can change in the lab that would make this faster some how.

**Comment by DawnmarieDesJardins** [comment]
@crpietschmann 
Thanks for checking.  The comment was made on a closed issue so I wanted to make sure you saw it.
