### ISSUE TITLE
AKS no longer support Kubernates 1.19.7,so it fails when deplying using arm template of lab 'Before the HOL'

### ISSUE THREAD

**Issue by teo-ma** [microsoft/MCW-Cloud-native-applications#262]
Hello,

Since AKS no longer support Kubernates version 1.19.7,it fails when deplying using arm template of lab 'Before the HOL'.May I suggest replace the  Kubernates 1.19.7 with 1.19.9.I tested on Azure West US Region and it worked,thanks.

Regards,

Teo

**Comment by DawnmarieDesJardins** [comment]
Closing as resolved with merge of PR #263
