### ISSUE TITLE
Issue in Exercise-4 Task-3

### ISSUE THREAD

**Issue by Karthikkc123** [microsoft/MCW-Cloud-native-applications#273]
[Exercise-4 Task-3 Step 6 & 7](https://github.com/microsoft/MCW-Cloud-native-applications/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Cloud-native%20applications.md#task-3-perform-a-rolling-update)

When user commit such changes and push to git repo, then GitHub action for content-web should start but it's not getting started. 

In the same section, the result should be auto update of application with new version, but this does not happen as there is not task in GitHub action which should access to k8s API and do deployment itself (as is e.g. https://docs.microsoft.com/en-us/azure/aks/kubernetes-action)

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #274
