### ISSUE TITLE
Issue in Before hands-on lab

### ISSUE THREAD

**Issue by Shivashant25** [microsoft/MCW-Cloud-native-applications#279]
In Task - 15: Setup CI Pipeline to Push Images, The content-web workflow is failing with the error mentioned in the screenshot below. Please look into this.

![image](https://user-images.githubusercontent.com/81952290/135836858-93d0c8af-3d6c-4629-b9b9-67f97c2c3942.png)

**Comment by Shivashant25** [comment]
Hi @hatboyzero, Hope you are doing well.

Recently our team had received feedback on this lab. All of them were talking about adding an introduction or few lines about what exactly we are doing in this particular lab which would enhance the understanding of the AKS. Even I feel the same, It's like we are running the commands without knowing what exactly is happening.

I hope that changes will enhance the lab. I have mentioned few feedback messages which we had received.

1. The lab doesn't teach Kubernetes concepts very well.  I recognize this is a VERY difficult subject but the lab doesn't really seem to explore any of the concepts within Kubernetes very well.  I think Kendall Roden was doing a GREAT job of making the K8s topics approachable without being too "in the weeds" but the lab doesn't really explain very much and just takes the readers through a cut and paste exercise for the most part.  For this to be an effective workshop in the future I think we'd need a 30-45 minute block before each page to explain the intentions of the page and the components and concepts that will be covered.

2. Giving an overview of what we are going to do in the lab, in the beginning, will be a great help, even though we have instructions given in the lab itself( i.e. step1 -we will be running the apps manually in the build agent, step2 - running the apps with docker containers in build agent, step3 - how to deploy using AKS). 

3. I think that going into the training, we were under the impression it would be more around the AKS offering, but we spent a lot of time setting up everything prior to AKS stuff and didn’t have time to get into the meat of the stuff.  I think it’s a good lab but really would have required a whole day's time.

**Comment by timahenning** [comment]
Hi @Shivashant25,

These are good suggestions.  We will be reviewing these suggestions in our upcoming update.

Tim
