### ISSUE TITLE
October 2021 Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Cloud-native-applications#280]

**Comment by timahenning** [comment]
- Use Bicep instead of ARM templates for AKS cluster deployment.
- Use PowerShell on local machine and AZ CLI, eliminating a large portion of the Before HOL.
- Add section using Visual Studio Code with the Kubernetes extension from Microsoft.
- Update the images and text based on Azure changes

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #290
