### ISSUE TITLE
Before the HOL - Task 10: Test the Starter Application - Step13

### ISSUE THREAD

**Issue by fatihdurgut** [microsoft/MCW-Cloud-native-applications#291]
Web application could not build. 
Node -v = v4.2.6

Error:
npm ERR! Linux 4.15.0-1113-azure
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

**Comment by DawnmarieDesJardins** [comment]
@faithdurgut - Hi Faith!  Thank you for bringing this to our attention.  I've assigned the author to take a look and double-check me, but we are nearly finished with a content update to this workshop that may fix the problem you're having.  It is on track to be published this week.  Can you wait for the new content?

**Comment by fatihdurgut** [comment]
Hello,  Sure I can wait. Thanks for the update.    Sent from Mail for Windows From: Dawnmarie DesJardinsSent: Wednesday, December 15, 2021 7:40 PMTo: microsoft/MCW-Cloud-native-applicationsCc: Fatih; AuthorSubject: Re: [microsoft/MCW-Cloud-native-applications] Before the HOL - Task 10: Test the Starter Application - Step13 (Issue ***@***.*** - Hi Faith! Thank you for bringing this to our attention. I've assigned the author to take a look and double-check me, but we are nearly finished with a content update to this workshop that may fix the problem you're having. It is on track to be published this week. Can you wait for the new content?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DawnmarieDesJardins** [comment]
Closing this issue with the merge of PR #290. Please see the updated content.
