### ISSUE TITLE
Before the HOL - Task 15: Setup CI Pipeline to Push Images - Step11

### ISSUE THREAD

**Issue by zagruby** [microsoft/MCW-Cloud-native-applications#292]
content-web.yml fails with the following line 63:
`        kubectl create namespace ingress-demo --dry-run -o json | kubectl apply -f -`

With the following error:
`Run kubectl create namespace ingress-demo --dry-run -o json | kubectl apply -f -
error: --dry-run flag without a value was specified. A value must be set: "none", "server", or "client".
error: no objects passed to apply
Error: Process completed with exit code 1.`

This can be fixed by amending the line to:
`        kubectl create namespace ingress-demo --dry-run=server -o json | kubectl apply -f -`

**Comment by DawnmarieDesJardins** [comment]
@zagruby - Hello!  Thank you for bringing this to our attention. I've assigned the author to take a look and double-check me, but we are nearly finished with an update to this workshop that condenses the Before the Hands-on Lab document a great deal. It is on track to be published this week. Please check back for the new content.

**Comment by DawnmarieDesJardins** [comment]
Closing this issue with the merge of PR #290. Please see the updated content.
