### ISSUE TITLE
Task 2: Deploy a service using the Azure Portal

### ISSUE THREAD

**Issue by fatihdurgut** [microsoft/MCW-Cloud-native-applications#293]
Create a namespace in Kubernetes where we will deploy our resources.

kubectl create namespace ingress-demo 

will give following error

fatih@Azure:~$ kubectl create namespace ingress-demo
Error from server (AlreadyExists): namespaces "ingress-demo" already exists

**Comment by hatboyzero** [comment]
There is an update to this workshop that is currently under review that will address this and other existing issues.

**Comment by DawnmarieDesJardins** [comment]
Closing this issue with the merge of PR #290. Please see the updated content.
