### ISSUE TITLE
Issue in Exercise 2 Task 2

### ISSUE THREAD

**Issue by Shivashant25** [microsoft/MCW-Cloud-native-applications#295]
In Exercise - 2> Task - 2> step - 10, I didn't face the expected error mentioned in the screenshot instead faced other errors after creating `api` deployment.

Expected error output:

![image](https://user-images.githubusercontent.com/81952290/147147755-beb90bfd-f3ce-42ef-a054-40d324e0f7ff.png)

Actual error: 

![image](https://user-images.githubusercontent.com/81952290/147147708-508b2190-e65b-46f4-ad9d-8f2830a1b1e5.png)

I further troubleshoot the issue and found that there are no container images created. In BHOL part, there are no steps are mentioned about creating api and web images. There are no steps mentioned about pushing the container images to the container registry. I tried creating new images and pushed the images to the container registry. It worked successfully and got the expected output.

![image](https://user-images.githubusercontent.com/81952290/147150529-6fa792a1-bc5a-4b6a-9c2d-b2c9af7e89e8.png).

Other Issues.
In BHOL> Task4> step - 3, after executing the script create_azure_resources.sh. SUFFIX value changes are not pushed to Fabmedical repo files. I used `cd ~/Fabmedical/.github/workflows/` path and pushed the changes to the Github repository and it worked.

In Eercise - 2>Task - 2> step - 19, Instruction to change the LOGINSERVER name  is not mentioned.

Please look into this issue. Thank you

**Comment by saimachi** [comment]
Hi @Shivashant25,

Thank you for bringing this issue to our attention. I am addressing these concerns on [my fork.](https://github.com/saimachi/MCW-Cloud-native-applications.git)
