### ISSUE TITLE
Task 3 : Unable to see "contentdb" in "Source" DB

### ISSUE THREAD

**Issue by abymsft** [microsoft/MCW-Cloud-native-applications#299]
Hi Team,

In Task 3, while configuring the "Database setting" step, I am unable to see the "contentdb" @ source (VM agent). Check screenshot below. 
Any ideas of how I can troubleshoot this?
![image](https://user-images.githubusercontent.com/50873759/150373342-19da3326-167f-461b-be93-d762eb267a97.png)

**Comment by saimachi** [comment]
Hi @abymsft,

I was unable to replicate this issue: the `contentdb` source database and its two collections were visible in the DMS wizard.

Please ensure that you executed the `create_and_seed_database.sh` bash script, as mentioned at the end of the Pre-HOL document, and that the following output was observed:

![image](https://user-images.githubusercontent.com/37318129/151110787-25ed6c65-7f05-4524-9f3e-2a1cb5a53b39.png)

If you want to re-run the script, you can use the following commands:

```bash
docker stop mongo
docker rm mongo
docker network rm fabmedical
```

**Comment by DawnmarieDesJardins** [comment]
@abymsft - Hello!  Were you able to move forward with the advice above?

**Comment by DawnmarieDesJardins** [comment]
No further questions received - closing issue.  Please reopen if necessary.

**Comment by cjpark-sapcsa** [comment]
![DB item is missing](https://user-images.githubusercontent.com/60184856/152538563-4ae7ef8c-1a1c-4739-8de3-cac24b402936.JPG)
@abymsft  Hi Abishek, i wonder how did you solve the issue? For me, i can't see DB name in the select cosmo DBname.

**Comment by DawnmarieDesJardins** [comment]
Reopening issue for further investigation.

**Comment by saimachi** [comment]
Hi @cjpark-sapcsa,

If Azure is unable to load the Cosmos DB instance automatically, try to paste the connection string manually from the Cosmos DB instance into the DMS window. Based on the image you posted, the issue you encountered is with DMS, rather than the lab instructions.

**Comment by cjpark-sapcsa** [comment]
Hi @saimachi  thanks for your tip. In the step of Exercise 1, Tasks3, before i reach this step, i don't see the labs guide whether we need to create a cosmos DB account. 
![after creation of dbaccount](https://user-images.githubusercontent.com/60184856/152669976-7322d546-f469-4e26-875f-7ce5f9b7e4aa.JPG)
 
after i create cosomo db account manually, the soureDB and connection strings are all appeared.   Please check whether the creation of cosmodb account need to before Tasks 3

**Comment by saimachi** [comment]
Hi @cjpark-sapcsa,

The creation of all lab resources, including the Cosmos DB account, occurred in the ARM template deployment step in Task 4 of the Before the HOL document.

**Comment by DawnmarieDesJardins** [comment]
@cjpark-sapcsa 
Hi CJ.  A quick check-in with you.  Were you able to move forward with the author's information above?

**Comment by cjpark-sapcsa** [comment]
@DawnmarieDesJardins   Yes.. good to go close the case
