### ISSUE TITLE
Issu in Exercise 1 Task 3

### ISSUE THREAD

**Issue by Shivashant25** [microsoft/MCW-Cloud-native-applications#300]
In [Exercise 1, task 3](https://github.com/microsoft/MCW-Cloud-native-applications/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Cloud-native%20applications.md#task-3-migrate-data-to-azure-cosmos-db) after migrating database to Cosmos DB, the data inside sessions is empty as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/81952290/152432710-80fb3514-f228-4477-8be8-b6d86651895c.png)

But in the lab guide, we see that screenshot is different in [Exercise 1, task 3, step 15](https://github.com/microsoft/MCW-Cloud-native-applications/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Cloud-native%20applications.md#task-3-migrate-data-to-azure-cosmos-db)

Facing an issue in further exercises while loading the web page, the session page content is not loading as expected as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/81952290/152432671-3be925a6-ca77-4840-aaaa-1b12e4082e75.png)

Please look into this issue.

**Comment by sumitmalik51** [comment]
Hi @DawnmarieDesJardins ,

Please treat this issue as a high priority as we are having this workshop every day.

Thanks

**Comment by saimachi** [comment]
Hi @Shivashant25,

Based on the image you posted, it looks like you executed the performance testing script (`perftest.sh`), even though this script is supposed to be executed in Exercise 3, Task 5. The local MongoDB initialization script (executed on the VM) populates the correct documents in the local instance.

For your second point, you should see the Sessions page populated with the "Perf Test" entries after Exercise 3, Task 5, as the performance testing script writes those entries to `sessions`.

**Comment by Shivashant25** [comment]
Hi @saimachi,

I had executed 'perftest.sh' in Exercise 3 task 5 and I understood your point. Thanks for the clarity.

In Exercise 4 Task 4 step 9, I got the Contoso webpage as output instead of getting a 404 error and in Exercise 4 Task 4 step 21, we got the same Contoso web page as output instead of the data. please look into it.

**Comment by Shivashant25** [comment]
Hi @saimachi,

I had executed 'perftest.sh' in Exercise 3 task 5 and I understood your point. I re-tested the lab. I didn't face any issues. We are good with the lab, Thanks for the clarity.

Closing this issue as it is resolved. 
Thank you.
