### ISSUE TITLE
Issue in Hands on lab (Before the HOL): Task 4, step 3 (AKS Version not available)

### ISSUE THREAD

**Issue by EstebanZ** [microsoft/MCW-Cloud-native-applications#305]
The ARM template tries to deploy a AKS version not available in any region (1.21.2).
https://github.com/microsoft/MCW-Cloud-native-applications/blob/f3dd219e8e5576605a4e3e79a4cdd6ea3830172d/Hands-on%20lab/arm/azuredeploy.json#L105

Today when I run Task 4 step 3:

`bash create_azure_resources.sh`

Output:
![image](https://user-images.githubusercontent.com/9389266/154562596-4e31a835-12d8-4123-be2f-9bc010817b55.png)

Note: Two days ago this version was available in West US and Brazil Southeast regions.

**Comment by aarsan** [comment]
I changed it to 1.21.9 and it worked.

**Comment by EstebanZ** [comment]
> I changed it to 1.21.9 and it worked.

Yeah! @aarsan , this is a workaround, but I need integrate it on main branch before labs assistants get same issues.

**Comment by hatboyzero** [comment]
Should be resolved by #308

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #308

**Comment by EstebanZ** [comment]
Hi, this change is not in main branch:

https://github.com/microsoft/MCW-Cloud-native-applications/blob/99b5385d603950b20b6c0cb99a26cebd0f39d7de/Hands-on%20lab/lab-files/developer/scripts/azuredeploy.json#L105

**Comment by DawnmarieDesJardins** [comment]
Reopened issue
@hatboyzero - Please advise.

**Comment by hatboyzero** [comment]
I see the necessary change in the main branch here

https://github.com/microsoft/MCW-Cloud-native-applications/blob/99b5385d603950b20b6c0cb99a26cebd0f39d7de/Hands-on%20lab/arm/azuredeploy.json#L105

**Comment by DawnmarieDesJardins** [comment]
@EstebanZ - Hi Esteban!  I see the updated .json as well.  Is it possible you ran the old version from a previous try?  Let me know if I can close this issue.

**Comment by EstebanZ** [comment]
Hi @DawnmarieDesJardins , now i see the updated .json. Thanks

**Comment by DawnmarieDesJardins** [comment]
Yay!  Thanks @EstebanZ - closing the issue.

**Comment by aarsan** [comment]
Still getting:

    Version 1.21.2 is not supported in this region

it looks like the template in the ARM directory is what was changed but the one in the:

    /Hands-On-Lab/lab-files/developer/scripts

needs to be changed.

**Comment by EstebanZ** [comment]
I was same problem from browser (github web)

Tme later from the browser the problem was solved (maybe it was cache.. I do not believe it but it is a possibility)

You can see the same commit but different value for key 😕
![image](https://user-images.githubusercontent.com/9389266/155897851-2757ebb4-435d-4360-90c1-a56f6317a914.png)


In Cloud Shell I was try git pull force, remove storage Account related to cloud shell to start from scratch but that do not work, tomorrow maybe try again..

**Comment by EstebanZ** [comment]
The path is not the same, create_azure_resources.sh use:

azuredeploy.json from /Hands-on lab/lab-files/developer/scripts/

sorry my bad 😄

**Comment by hatboyzero** [comment]
#311 includes the additional change necessary to update this version in the correct file, so this should be resolved when that gets accepted and merged.
