### ISSUE TITLE
Issue in Hands on lab (Before the HOL): Task 4, step 1 (missing scope in docs)

### ISSUE THREAD

**Issue by EstebanZ** [microsoft/MCW-Cloud-native-applications#307]
The following link assign repo scope to the PAT:

https://github.com/microsoft/MCW-Cloud-native-applications/blob/f3dd219e8e5576605a4e3e79a4cdd6ea3830172d/Hands-on%20lab/Before%20the%20HOL%20-%20Cloud-native%20applications.md?plain=1#L150

But to run create_azure_resources.sh the scopes required are:
-Workflow
-read:org

![image](https://user-images.githubusercontent.com/9389266/154695752-568084e9-46f6-4f96-8735-5e86dd42c6a5.png)

**Comment by hatboyzero** [comment]
Should be resolved by #308

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #308
