### ISSUE TITLE
AuthorizationFailed error during aks-set-context in rolling update task (ex 4 task 3)

### ISSUE THREAD

**Issue by adamkimsft** [microsoft/MCW-Cloud-native-applications#313]
This error occurs when doing the rolling update:

Run Azure/aks-set-context@v1
  with:
    creds: ***
    cluster-name: fabmedical-ak4
    resource-group: Fabmedical-ak4
  env:
    imageRepository: content-api
    resourceGroupName: Fabmedical-ak4
    clusterName: fabmedical-ak4
    containerRegistryName: ***
    containerRegistry: ***.azurecr.io
    dockerfilePath: ./content-api
    tag: 1936045933
Error: ***"error":***"code":"AuthorizationFailed","message":"The client '90c1[2](https://github.com/adamkimsft/Fabmedical/runs/5428593301?check_suite_focus=true#step:5:2)77d-db77-[4](https://github.com/adamkimsft/Fabmedical/runs/5428593301?check_suite_focus=true#step:5:4)[5](https://github.com/adamkimsft/Fabmedical/runs/5428593301?check_suite_focus=true#step:5:5)80-a900-b[6](https://github.com/adamkimsft/Fabmedical/runs/5428593301?check_suite_focus=true#step:5:6)4092a[7](https://github.com/adamkimsft/Fabmedical/runs/5428593301?check_suite_focus=true#step:5:7)f2cc' with object id '90c1277d-db77-45[8](https://github.com/adamkimsft/Fabmedical/runs/5428593301?check_suite_focus=true#step:5:8)0-a[9](https://github.com/adamkimsft/Fabmedical/runs/5428593301?check_suite_focus=true#step:5:9)00-b64092a7f2cc' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/accessProfiles/listCredential/action' over scope '/subscriptions/1d5e6dd7-916f-4aa0-9abe-0cf4f655cf2d/resourceGroups/Fabmedical-ak4/providers/Microsoft.ContainerService/managedClusters/fabmedical-ak4/accessProfiles/clusterAdmin' or the scope is invalid. If access was recently granted, please refresh your credentials."***

This is the yaml step involved:

    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: '${{ env.clusterName }}'
        resource-group: '${{ env.resourceGroupName }}'

It uses AZURE_CREDENTIALS to connect to AKS to set the context.  AZURE_CREDENTIALS is set in create_azure_resources.sh:

AZURE_CREDENTIALS=$(az ad sp create-for-rbac --sdk-auth)

GITHUB_TOKEN=$MCW_GITHUB_TOKEN
cd ~/Fabmedical
echo $GITHUB_TOKEN | gh auth login --with-token
gh secret set ACR_USERNAME -b "$ACR_USERNAME"
gh secret set ACR_PASSWORD -b "$ACR_PASSWORD"
gh secret set AZURE_CREDENTIALS -b "$AZURE_CREDENTIALS" 

The call to create-for-rbac is not giving enough permissions to perform this step.  I worked around it by adding the service principal created as a contributor role in the RBAC for AKS.  Perhaps there's a better way to do this.  the --sdk-auth is deprecated.  I'm guessing theres a --scope parameter appropriate for this.

**Comment by DawnmarieDesJardins** [comment]
@adamkimsft - Hi Adam.  The error information you received didn't come through.  Please repost it for us.  Thanks!

**Comment by adamkimsft** [comment]
Yes, I accidentally hit the post button.  Adding the rest of the info now.

**Comment by adamkimsft** [comment]
Please see updated first post.

**Comment by hatboyzero** [comment]
Recent changes to how az-cli creates service principals for RBAC do require us to change our call to 

```sh
AZURE_CREDENTIALS=$(az ad sp create-for-rbac --scopes <Azure Subscription Resource ID>)
```

For now, that should be a sufficient workaround - I will get changes around this into a pull request later today.

**Comment by timahenning** [comment]
Re-opening for further investigation.

**Comment by hatboyzero** [comment]
The PR associated with #324 should resolve this if it is still occurring.

**Comment by DawnmarieDesJardins** [comment]
@adamkimsft - Hi Adam!  I've merged Matt's PR, please test and let us know if you're still finding this issue.

**Comment by adamkimsft** [comment]
Yes, this fixed it!  Thanks.
