### ISSUE TITLE
I found a wrong step description on Step 6 of Excerse 4 Task 4 

### ISSUE THREAD

**Issue by teo-ma** [microsoft/MCW-Cloud-native-applications#315]
Hi,
I do love these labs as it can help more people experience AKS.  

I found a wrong step description on Step 6 of Excerse 4 Task 4 when doing this.I figure it out with boldface

Paste the following as the contents. Be sure to replace the following placeholders in the script:

[INGRESS PUBLIC IP]: Replace this with the IP Address copied from **step 5.** ----------<Should Be step 4>
[AKS NODEPOOL RESOURCE GROUP]: Replace with the name of the Resource Group copied from **step 6.**-----<Should Be step 5>

Could you kindly help to check again?

Thanks，
Teo

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #317
