### ISSUE TITLE
Github Actions Issue on Step 10 of Exercise 4 Task3

### ISSUE THREAD

**Issue by teo-ma** [microsoft/MCW-Cloud-native-applications#316]
Hi ,

I met a Github Actions issue when building and pushing Docker Image via [content-web.yml](https://github.com/teo-ma/Fabmedical/blob/main/.github/workflows/content-web.yml) and [content-api.yml](https://github.com/teo-ma/Fabmedical/blob/main/.github/workflows/content-api.yml)

The error like **"You have an error in your yaml syntax on line 29"**
<img width="867" alt="iShot2022-03-15 11 20 06" src="https://user-images.githubusercontent.com/16115524/158299464-32a1f801-b433-477c-8e0c-e1f1beea5f5d.png">

I can not find the syntax error on the two yamls.Has anyone else met the same issue?Or cloud you help me to resolve this?

Any suggestions would be much appreciated.

Regards,
Teo

**Comment by hatboyzero** [comment]
You have indented the last step in the job one too many spaces.  Verified the fix for your content-web.yaml in YAMLlint was nothing more than removing one space from the indentation of all the lines in the very last step of your defined workflow.

**Comment by timahenning** [comment]
Hi @teo-ma,

We are closing this issue.  Let us know if the provided solution does not work and we can reopen the issue for you.
