### ISSUE TITLE
Incorrect working directories in Ex 4 Task 3

### ISSUE THREAD

**Issue by adamkimsft** [microsoft/MCW-Cloud-native-applications#323]
Step 2 should cd to ~/Fabmedical/ (not ~/Fabmedical/content-web).  Otherwise, the kubectl get commands doesn't overwrite our original yml files which is in the Fabmedical directory.
Step 3 needs to cd to ~/Fabmedical/content-web due to the fix in previous step.

Also in Step 2, file extension should be yml, not yaml.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #326

**Comment by adamkimsft** [comment]
You forgot this correction mentioned when I opened it:

Also in Step 2, file extension should be yml, not yaml.

**Comment by DawnmarieDesJardins** [comment]
Reopened issue to address comments above.

**Comment by DawnmarieDesJardins** [comment]
PR merged, thanks Adam.
