### ISSUE TITLE
Issue in Before Hands-on lab

### ISSUE THREAD

**Issue by shivashant25** [microsoft/MCW-Cloud-native-applications#331]
In Before Hands-on lab> Task 6> step 1, The **content-api** docker image build is failing with errors mentioned below. Please check on this as we have upcoming workshops.

Step 8/13 : RUN npm install
 ---> Running in 44f843cde1b1

**ERRORS:**:

npm WARN engine saslprep@1.0.3: wanted: {"node":">=6"} (current: {"node":"4.9.1","npm":"2.15.11"})
npm ERR! Linux 4.15.0-1113-azure
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.11
npm ERR! path /usr/src/app/node_modules/mongoose/node_modules/@types/mongodb/node_modules/@types/node/package.json
npm ERR! code ENOTDIR
npm ERR! errno -20
npm ERR! syscall open

npm ERR! ENOTDIR: not a directory, open '/usr/src/app/node_modules/mongoose/node_modules/@types/mongodb/node_modules/@types/node/package.json'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

![image](https://user-images.githubusercontent.com/81952290/173346198-31b44083-2901-4474-a468-e6463a52d33e.png)

**Comment by shivashant25** [comment]
@DawnmarieDesJardins / @timahenning, Can you please check on this issue as we have multiple lab schedules on 14/06/2022

**Comment by DawnmarieDesJardins** [comment]
@shivashant25 
We will do our best, but less than 24 hours' notice is not an acceptable amount of time for a review/fix.  Please make sure you are testing well ahead of any presentations.

**Comment by hatboyzero** [comment]
This looks to be related to recent updates to NPM packages.  I have a fix - testing the Docker build for the associated change (update to node:18.3-alpine docker base image) before creating a PR.  Should be a few moments.

**Comment by hatboyzero** [comment]
PR is up for review.

**Comment by DawnmarieDesJardins** [comment]
@shivashant25 
A fix PR has been merged.  Please test and confirm ASAP.

**Comment by sumitmalik51** [comment]
Thanks @hatboyzero @DawnmarieDesJardins , for the quick fix, we are trying right now and will update in sometime. Thanks

**Comment by DawnmarieDesJardins** [comment]
Thanks Shivashant - @hatboyzero is a rockstar! Closing this issue as resolved.
